language: node_js

node_js:
  - 10.15.3

cache:
  directories:
    - ./node_modules

before_script:
  - npm install --prefix fe-20_final_project

script:
  - npm run test --prefix fe-20_final_project
