language: node_js

node_js:
  - 14.16.0

cache:
  directories:
    - ./node_modules

before_install:
  - npm install codecov --save-dev
  - npm install -g istanbul
before_script:
  - npm install --prefix ./

script:
  - npm run test --prefix ./
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
./node_modules/.bin/codecov

after_success:
  - codecov
