language: node_js

node_js:
  - 14.16.0

cache:
  directories:
    - ./node_modules

before_install:
  - sudo pip install codecov

before_script:
  - npm install --prefix ./

script:
  - npm run test --prefix ./
  - phpunit --coverage-clover=coverage.xml

after_success:
  - codecov
