language: node_js

node_js:
  - 14.16.0

cache:
  directories:
    - ./node_modules

before_script:
  - npm install --prefix ./
  - pip install pytest pytest-cov

script:
  - npm run test --prefix ./
  - pytest --cov=mypkg --cov-report term --cov-report xml:coverage.xml
  # - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
