language: node_js

node_js:
  - 14.16.0

cache:
  directories:
    - ./node_modules

before_script:
  - npm install --prefix ./

script:
  - npm run test --prefix ./

after_success:
  - npm run coveralls
