language: node_js

node_js:
  - 14.16.0

cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g codecov

before_script:
  - npm install --prefix ./

script:
  - npm run test --prefix ./
  - istanbul cover https://codecov.io/bash --reporter lcovonly -- -R spec
  - codecov
