language: node_js

node_js:
  - 14.16.0

cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g codecov

before_script:
  - npm install --prefix ./

script:
  - npm run test --prefix ./
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
