codecov:
  token: '8c6b1530-b19d-46aa-b688-1c88b2d4c88d'
  bot: 'codecov-io'
  ci:
    - 'travis.org'
  strict_yaml_branch: 'auth'
  max_report_age: false
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
